// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
     apiKey: "AIzaSyDoTsCj560kq1tSZS4MVSQ_VbcmF26ijdE",
    authDomain: "recipes-ce709.firebaseapp.com",
    projectId: "recipes-ce709",
    storageBucket: "recipes-ce709.firebasestorage.app",
    messagingSenderId: "826006463661",
    appId: "1:826006463661:web:94839cf5b84568942cd224"
  );

  static const FirebaseOptions android = FirebaseOptions(
     apiKey: "AIzaSyDoTsCj560kq1tSZS4MVSQ_VbcmF26ijdE",
    authDomain: "recipes-ce709.firebaseapp.com",
    projectId: "recipes-ce709",
    storageBucket: "recipes-ce709.firebasestorage.app",
    messagingSenderId: "826006463661",
    appId: "1:826006463661:web:94839cf5b84568942cd224"
  );
} 


